server:
  port: 9000
  servlet:
      contextPath: /poms # 开发环境>项目名
#  tomcat:
#    uri-encoding: UTF-8

spring:
  profiles:
    active: dev
  datasource: # database configuration
#    type: com.mchange.v2.c3p0.ComboPooledDataSource # C3P0数据库连接池配置(如果不用C3P0，可删除本行)
    url : jdbc:mysql://johnnyzen.cn:3306/test201904?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username : xxx
    password : xxxxxxxx
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    database: 0 # Redis数据库索引（默认为0）
#    host: 127.0.0.1 # Redis服务器地址
#    port: 6379 # 服务器连接端口
#    password: 123456 # Redis服务器连接密码（默认为空）
#    timeout: 1000 # 连接超时时间（毫秒）
#    pool:
#      max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
#      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-idle: 10 # 连接池中的最大空闲连接
#      min-idle: 0 # 连接池中的最小空闲连接
  jpa:
    database : MYSQL
    show-sql : true  # 在控制台可以看到SQL语句
    hibernate:
      ddl-auto : update # update create create-drop validate
      naming-strategy : org.hibernavedNamingStrategy
      dialect : org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: true # SQL字段类型转换格式化
  mvc: # SpringMVC
    view: # 定位模板的目录
      prefix: classpath:/templates/  # 模板引擎thymeleaf-默认目录：src/main/resources/templates/
      suffix: .html # 返回页面的默认后缀格式
  devtools:
    restart:
      additional-path: src/main/java #添加哪个目录的文件需要restart
#      exclude: static/**,public/**

# 关闭Application
endpoints:
  shutdown:
    enabled: true #启用shutdown
    sensitive: false #禁用密码验证


#### 用户自定义
article:
  summaryAPIUrl: http://localhost:8000/poms/analysis/summary/api
  keywordsAPIUrl: http://localhost:8000/poms/analysis/keywords/api
file:
  staticAccessRootPath: /public/**
  staticRealRootPath: /home/ubuntu/forget-note-words/file/public/
##  staticRealRootPath: C:/Users/千千寰宇/Desktop/public/
mail:
#  protocol: http # 协议 # 本字段废弃，由程序方法参数动态设定
#  serverDomain: localhost # johnnyzen.cn # 本服务器域名或者IP # 本字段废弃，由程序方法参数动态设定
#  port: 9000 # 本字段废弃，由程序方法参数动态设定
#  contextPath: /poms # 开发环境>项目名  # 本字段废弃，由程序方法参数动态设定
#  actionPath: /register-activate/view #请求激活服务的URI  # 本字段废弃，由程序方法参数动态设定
  host: smtp.qq.com # 指定发送邮件的主机smtp.qq.com(QQ)|smtp.163.com(网易)
#  subject: 【速读APP】 # 本字段废弃，由程序方法参数动态设定
  senderEmail: xxxxxxxx@qq.com # 发件人邮箱
#  authCode: pmbemumvpqafjbea # 授权码
  authCode: xxxxxxxx